#!/usr/bin/env bash

# Merge environment variables into the main site configuration.
vars='$FPM_HOST'
envsubst "$vars" \
  < /usr/local/etc/nginx/site.conf.template \
  > /etc/nginx/conf.d/default.conf

# Run Nginx in non-daemonized mode.
exec authbind nginx -g "daemon off;"
